name: ci_build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - dpp
          - itg
          - pjt
jobs:
  build:
    runs-on: windows-latest # Or ubuntu-latest for Linux runners

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get GitHub Actor in PowerShell
      shell: pwsh # Specifies PowerShell Core (pwsh) as the shell
      run: |
        $githubActor = "${{ github.actor }}"
        Write-Host "The GitHub Actions actor is: $githubActor"
        
        # You can use this variable for further logic
        if ($githubActor -eq "your-username") {
            Write-Host "Hello, you triggered this workflow!"
        } else {
            Write-Host "Someone else triggered this workflow."
        }