name: ci_build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - dpp
          - itg
          - pjt
jobs:
  build:
    runs-on: windows-latest # Or ubuntu-latest for Linux runners

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get GitHub Actor in PowerShell
      shell: pwsh # Specifies PowerShell Core (pwsh) as the shell
      run: |
        $githubActor = "${{ github.actor }}"
        Write-Host "The GitHub Actions actor is: $githubActor"
        
        # You can use this variable for further logic
        if ($githubActor -eq "your-username") {
            Write-Host "Hello, you triggered this workflow!"
        } else {
            Write-Host "Someone else triggered this workflow."
        }
        $url = "https://sendpush-iadldraf3a-uc.a.run.app/broadcast"
        $branch = "${{ github.ref_name }}"
        $body = @{
          title = "✅ 빌드 성공"
          body  = "브랜치: $branch 사용자: $githubActor가 ${{ github.event.inputs.environment }} 빌드에 성공했습니다."
        } | ConvertTo-Json -Compress

        Invoke-RestMethod -Uri $url `
                          -Method Post `
                          -Body $body `
                          -ContentType "application/json"
